# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='wen',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='userinfor',
            table='info_ation',
        ),
    ]
